development:
  app_id: ENV["fb_app_id"]
  secret: ENV["fb_secret"]
  call_back: http://localhost:3000/users/auth/facebook/callback

production:
  app_id: ENV["fb_app_id"]
  secret: ENV["fb_secret"]
  call_back: https://eggplant-sale.herokuapp.com/users/auth/facebook/callback