# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222

default: &default
  merchant_id: ENV["merchant_id"]
  hash_key: ENV["hash_key"]
  hash_iv: ENV["hash_iv"]
  url: https://ccore.spgateway.com/MPG/mpg_gateway

development:
  <<: *default
  notify_url: http://requestbin.fullcontact.com/xrzi3wxs

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  notify_url: https://eggplant-sale.herokuapp.com/